# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: 
  branches:
    include:
    - dev
  paths:
    include:
    - 'files/F5_PEPS_REC_OP.json'

pool: marvin-ansible

steps:

- script: scripts/Playbook-Launcher.sh
  displayName: 'run playbook'

