---

- name: "Yaml VIP file transfert.rec.galec.fr.yml based on VIP_PROFILE_SSLOFFLOAD_REC_STANDARD"
  hosts: F5
  gather_facts: no
  connection: local
#####################
#       VARS        #
#####################
  vars:
    continue_var: OUI
#Provider vars
    provider:
      server: 192.168.0.250
      user: admin
      password: admin
      validate_certs: no


#Global VAR Should Come From INPUT.json
    env: qlf
    app: toto
    profile: vip_profile_ssloffload_rect_standard
    vsip : "192.168.156.16"
    pmhost:
     - 172.30.15.1
     - 172.30.15.2
     - 172.30.15.3
     - 172.30.15.4

#Var calculated from INPUT.json vars
    fqdn: '{{ vars["app"]+"."+vars["env"]+".galec.fr" if env != "prd" else vars["app"]+".galec.fr" }}'
    dom:  '{{ vars["env"]+".galec.fr" if env != "prd" else "galec.fr" }}'
    vsname: "vs_{{fqdn}}"
    plname: "p_{{fqdn}}"
    client_ssl_parent_profile : "clientssl_wildcard.{{dom}}-template"
    client_ssl_profile: "clientssl_{{fqdn}}"



#Var calculated frome VIP Profile 
    vsport: "443"
    pmport: "80"
    monitors : "tcp"
    snat : "Automap"
    all_profiles:
     - '{{client_ssl_profile}}'
     - tcp

#Delete or Create/Modify    
    state: "absent"


  tasks:

    - name: Checking Vars
      debug:
        msg: 
          client_ssl_parent_profile: '{{ client_ssl_parent_profile }}'
          client_ssl_profile: '{{ client_ssl_profile }}'


    - name: Gathering ltm profile '{{ client_ssl_parent_profile }}'
      bigip_command:
        commands: list ltm profile client-ssl '{{ client_ssl_parent_profile }}'
        provider: "{{ provider }}"
      register: client_ssl_parent_profile_list

    - name : print out sslprofile list
      debug:
        msg: "{{client_ssl_parent_profile_list.stdout}}"

    - name : Register Continue Playbook variable
      when: '"not found" in "{{client_ssl_parent_profile_list.stdout}}"'
      set_fact:
        continue_var: 'NON'

    - name : Register Continue Playbook variable
      when: state == "absent"  
      set_fact:
        continue_var: 'OUI'


    - name : print out continue_var
      debug:
        msg:
          Peut_on_executer_le_playbook : "{{continue_var}}"


    - name: Adjust virtual server {{ vsname }}
      bigip_virtual_server:
        provider: "{{ provider }}"
        name: "{{ vsname }}"
        destination: "{{ vsip }}"
        port: "{{ vsport }}"
        description: "Web App"
        snat: "{{ snat }}"
        state: "{{ state }}"
      when: continue_var != "NON"

    - name: Create client SSL profile
      bigip_profile_client_ssl:
        provider: "{{ provider }}"
        state: "{{ state }}"
        name: "{{ client_ssl_profile }}"
        parent: "{{ client_ssl_parent_profile }}"
      when: continue_var != "NON"

    - name: Create web servers pool {{ plname }}
      bigip_pool:
        state: "{{ state }}"
        partition: Common
        name: "{{ plname }}"
        lb_method: "round-robin"
        monitor_type: "and_list"
        monitors: "{{ monitors }}"
        provider: "{{ provider }}"
      when: continue_var != "NON"

    - name: Create nodes
      bigip_node:
        provider: "{{ provider }}"
        name: "{{ item }}"
        host: "{{ item }}"
        state: "{{ state }}"
      with_items: "{{ pmhost }}"
      when: continue_var != "NON"


    - name: Add nodes to pool {{ plname }}
      bigip_pool_member:
        provider: "{{ provider }}"
        host: "{{ item }}"
        port: "{{ pmport }}"
        pool: "{{ plname }}"
        state: "{{ state }}"
      with_items: "{{ pmhost }}"
      when: state == "present"


    - name: Update a VS
      bigip_virtual_server:
        provider: "{{ provider }}"
        name: "{{ vsname }}"
        pool: "{{ plname }}"
        all_profiles : "{{ all_profiles }}"
        state: "{{ state }}"
      when: state == "present"
